name: 'sumup'
version: '1.9.0'

profile: 'sumup'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

vars:
    "dbt_date:time_zone": "Europe/Berlin"

models:
  sumup:
    # i added this schema setup because staging should be only available to the data team
    # while the reporting layer, core and mart should be available to the reporting systems and end users
    # this way it makes it easy to grant selects to the right users on this schema
    # in case we would do an intermediate layer for more complex calculations put the folder under core
    # and create a new intermediate schema here.  
    staging:
      schema: staging
    core:
      schema: core
      marts:
        schema: mart

  post-hook:
    - "GRANT SELECT ON {{ this }} TO postgres"

on-run-end:  
  - "GRANT USAGE ON SCHEMA {{ schema }} TO postgres"