name: 'sumup'
version: '1.9.0'

profile: 'sumup'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

vars:
    "dbt_date:time_zone": "Europe/Berlin"

models:
  sumup:
    # Config indicated by + and applies to all files under models/example/
    staging:
      schema: staging
    core:
      schema: core

  post-hook:
    - "GRANT SELECT ON {{ this }} TO postgres"

on-run-end:  
  - "GRANT USAGE ON SCHEMA {{ schema }} TO postgres"